apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.ctprinter'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()
useExpoPublishing()

android {
  namespace "expo.modules.ctprinter"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  // 驰腾官方 SDK（厂商提供的 jar）
  implementation fileTree(dir: "libs", include: ["*.jar"])
}
